CurbashaApi/Controllers/Admin/UserOrdersAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CurbashaApi.Areas.Identity.Entity;
using CurbashaApi.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace CurbashaApi.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserOrdersAdminController : Controller
    {
        private readonly CurbashaApiContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public UserOrdersAdminController(CurbashaApiContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: UserOrdersAdmin/Index
        public async Task<IActionResult> Index()
        {
            ViewBag.userNames = _userManager.Users.ToList();
            return View(await _context.AspUserOrder.ToListAsync());
        }

        // GET: UserOrdersAdmin/User/IdUser
        public async Task<IActionResult> User(string id)
        {
            ViewBag.userNames = _userManager.Users.ToList();
            return View("Index", await _context.AspUserOrder.Where(o => o.User.Id == id).ToListAsync());
        }

        // GET: UserOrdersAdmin/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AspUserOrder == null)
            {
                return RedirectToAction("Error404", "Admin");
            }

            var aspUserOrder = await _context.AspUserOrder
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aspUserOrder == null)
            {
                return RedirectToAction("Error404", "Admin");
            }
            ViewBag.SelectedItems = _context.AspOrderItems.Where(o => o.OrderId == id).ToList();
            return View(aspUserOrder);
        }

        // GET: UserOrdersAdmin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.AspUserOrder == null)
            {
                return RedirectToAction("Error404", "Admin");
            }

            var aspUserOrder = await _context.AspUserOrder
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aspUserOrder == null)
            {
                return RedirectToAction("Error404", "Admin");
            }

            return View(aspUserOrder);
        }

        // POST: UserOrdersAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.AspUserOrder == null)
            {
                return Problem("Entity set 'CurbashaApiContext.AspUserOrder'  is null.");
            }
            var aspUserOrder = await _context.AspUserOrder.FindAsync(id);
            if (aspUserOrder != null)
            {
                var activeProductItems = _context.AspOrderItems.Where(ap => ap.OrderId == aspUserOrder.Id);
                _context.AspOrderItems.RemoveRange(activeProductItems);
                _context.AspUserOrder.Remove(aspUserOrder);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AspUserOrderExists(int id)
        {
          return _context.AspUserOrder.Any(e => e.Id == id);
        }
    }
}

CurbashaApi/Controllers/Admin/UsersAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using CurbashaApi.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CurbashaApi.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly CurbashaApiContext _context;

        public UsersAdminController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager, CurbashaApiContext context)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _context = context;
        }

        // GET: UsersAdmin/Index
        public IActionResult Index()
        {
            ViewBag.roles = _roleManager.Roles.ToList();
            return View(_userManager.Users.ToList());
        }

        // GET: UsersAdmin/Delete/5
        public async Task<IActionResult> Delete(string? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error404", "Admin");
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return RedirectToAction("Error404", "Admin");
            }

            return View(user);
        }

        // POST: UsersAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                var lastUserCart = _context.AspUserOrder.LastOrDefault(o => o.User.Id == id);
                if (lastUserCart != null && lastUserCart.IsActive)
                {
                    var activeProductItems = _context.AspOrderItems.Where(ap => ap.OrderId == lastUserCart.Id);
                    _context.AspOrderItems.RemoveRange(activeProductItems);
                    _context.AspUserOrder.Remove(lastUserCart);
                }
                await _userManager.DeleteAsync(user);
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

CurbashaApi/Controllers/RolesController.cs
using CurbashaApi.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CurbashaApi.Controllers
{
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<IdentityUser> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

CurbashaApi/Views/UsersAdmin/Delete.cshtml
@model Microsoft.AspNetCore.Identity.IdentityUser
@{
    ViewData["Title"] = "Users";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            Role
        </dt>

        <dd>
            Role
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger mr-2" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CurbashaApi/Views/UsersAdmin/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityUser>
@{
    ViewData["Title"] = "Users";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var roles = ViewBag.roles as IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTable Users</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.UserName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PhoneNumber)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Email)
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UserName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "Roles", new { userid = item.Id })">
                                        <i class="btn btn btn-info btn-sm">Edit Roles</i>
                                    </a>
                                    @*<a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-userid="@item.Id">Edit Role</a>*@
                                    <a href="@Url.Action("User", "UserOrdersAdmin", new { id = item.Id })">
                                        <i class="btn btn-warning btn-sm my-1">Show Orders</i>
                                    </a>
                                    <a href="@Url.Action("Delete", "UsersAdmin", new { id = item.Id })">
                                        <i class="btn btn-danger btn-sm">Delete</i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>