CurbashaApi/Controllers/BasketProductController.cs
using System.Linq;
using System.Threading.Tasks;
using CurbashaApi.Areas.Identity.Entity;
using CurbashaApi.Data;
using CurbashaApi.Models;
using CurbashaApi.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CurbashaApi.Controllers
{
    public class BasketProductController : Controller
    {
        private readonly CurbashaApiContext _context;

        public BasketProductController(CurbashaApiContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Basket()
        {
            var delivery = GetDelivery();

            if (delivery == null || delivery.IsActive == false)
            {
                return RedirectToAction("Shop", "Shop");
            }
            
            var items = _context.AspOrderItems.Select(s => s).Where(w => w.OrderId == delivery.Id);

            ViewBag.total = _context.AspOrderItems.Select(s => s).Where(w => w.OrderId == delivery.Id)
                .Sum(s => s.Price * s.Quantity);


            return View(items);
        }

        [HttpPost]
        public IActionResult Basket(BasketViewModel model, int id)
        {
            var item = GetItem(id);
            _context.AspOrderItems.Remove(item);
            _context.SaveChanges();


            return Json("Basket");
        }

        [HttpPost]
        public async Task<IActionResult> Checkout()
        {
            var delivery = GetDelivery();

            var items = _context.AspOrderItems.Where(w => w.OrderId == delivery.Id);
            if (items.Count() != 0)
            {
                delivery.IsActive = false;
                _context.Update(delivery);
                await _context.SaveChangesAsync();

                return View(delivery);
            }
            return RedirectToAction("Home", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> ChangeOrderItemQuantity(int id, string symbol)
        {
            var orderItem = await _context.AspOrderItems.FirstOrDefaultAsync(f => f.Id == id);

            if (orderItem is null)
                return BadRequest("Order item not found");

            if (orderItem.Quantity <= 1 && symbol == "-")
                return Ok();

            switch (symbol)
            {
                case "+":
                    ++orderItem.Quantity;
                    break;

                case "-":
                    --orderItem.Quantity;
                    break;

                default:
                    return BadRequest("Symbol not valid");
            }

            _context.AspOrderItems.Update(orderItem);
            await _context.SaveChangesAsync();

            return Ok();
        }

        private AspUserOrder GetDelivery()
        {
            var currentUser = _context.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);

            var basket = Request.Cookies["guest"];


            if (currentUser == null)
            {
                currentUser = _context.Users.FirstOrDefault(u => u.Id == basket);
            }

            return _context.AspUserOrder.OrderBy(o => o.Id).LastOrDefault(u => u.User == currentUser);
        }


        private AspOrderItem GetItem(int id)
        {
            return _context.AspOrderItems.FirstOrDefault(i => i.Id == id);
        }
    }
}

CurbashaApi/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    @*<link href="~/Admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">*@
    <script src="https://kit.fontawesome.com/6109ed980b.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Admin/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="~/Admin/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

    <!-- Custom styles for table page -->
    <link href="~/Admin/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">


</head>
<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-area="" asp-controller="Home" asp-action="Home">
                <div class="sidebar-brand-text mx-3">Curbasha <sup>Api</sup></div>
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Nav Item - Dashboard -->

            <li class="nav-item active">
                <a class="nav-link" asp-controller="Admin" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Home">
                    <i class="fas fa-fw fa-shopping-cart"></i>
                    <span>Get back to Shop</span>
                </a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Heading -->
            <div class="sidebar-heading">
                Tables
            </div>
            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                @*Products*@
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-product-hunt"></i>
                    <span>Product</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Product Records:</h6>
                        <a class="collapse-item" href="~/ProductAdmin/Index">Product List</a>
                        <a class="collapse-item" href="~/ProductAdmin/Create">Product Create</a>
                    </div>
                </div>
            </li>
            <li class="nav-item">
                @*Selections*@
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Sections</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Selections Records:</h6>
                        <a class="collapse-item" href="~/SelectionsAdmin/Index">Selections List</a>
                        <a class="collapse-item" href="~/SelectionsAdmin/Create">Selections Create</a>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                @*Users*@
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseFour"
                   aria-expanded="true" aria-controls="collapseFour">
                    <i class="fas fa-fw fa-user"></i>
                    <span>Users</span>
                </a>
                <div id="collapseFour" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Users Records:</h6>
                        <a class="collapse-item" href="~/UsersAdmin/Index">Users List</a>
                        <a class="collapse-item" href="~/Roles/Index">Users Roles</a>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                @*Orders*@
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseThree"
                   aria-expanded="true" aria-controls="collapseThree">
                    <i class="fas fa-fw fa-shopping-basket"></i>
                    <span>Orders</span>
                </a>
                <div id="collapseThree" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Orders Records:</h6>
                        <a class="collapse-item" href="~/UserOrdersAdmin/Index">Orders List</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.Identity.Name</span>
                                <img class="img-profile rounded-circle"
                                     src="~/Admin/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" asp-action="User" asp-controller="User">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Home", "Home", new { area = "" })" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Content Row -->
                    <div class="row">
                        <div class="container body-content">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Curbasha 2022</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Home", "Home", new { area = "" })" >Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*Core plugin JavaScript*@
    <script src="~/Admin/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/Admin/js/sb-admin-2.min.js"></script>

    <script src="~/Admin/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Admin/js/demo/datatables-demo.js"></script>

    <!-- Page level plugins -->
    <script src="~/Admin/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Admin/js/demo/datatables-demo.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CurbashaApi/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager




<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

    <title>@ViewData["Title"] - CurbashaApi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CurbashaApi.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/responsive.css" asp-append-version="true" />

</head>
<body>  
    <header class="header_section">
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container">
            <a class="navbar-brand" href="/Home/Home">
                <img src="@Url.Content("~/images/logo.png")">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav  ">
                    <li class="nav-item">
                        <a class="nav-link" href="/Home/Home"> Home </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Shop/Shop">Shop </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Contact/Contact">Contact us</a>
                    </li>
                </ul>
                <div class="user_option">
                        @if (!SignInManager.IsSignedIn(User))
                        {
                            <a asp-area="Identity" asp-page="/Account/Login" style="margin-right: 20px;">
                                <img src="@Url.Content("~/images/user.png")" alt="">
                                <span>
                                    Login
                                </span>
                            </a>
                        }
                        else{
                            <a asp-area="Identity" asp-page="/Account/Manage/Index" style="margin-right: 20px;">
                                <img src="@Url.Content("~/images/user.png")" alt="">
                                <span>
                                    Profile
                                </span>
                            </a>

                        }
                        <a asp-area="" asp-controller="BasketProduct" asp-action="Basket" style="margin-right: 20px;">
                        <img src="@Url.Content("~/images/shopping-cart.png")" alt="">
                        <span>
                            Cart
                        </span>
                    </a>

                </div>
            </div>
            <div>
                <div class="custom_menu-btn ">
                    <button>
                        <span class=" s-1">

                        </span>
                        <span class="s-2">

                        </span>
                        <span class="s-3">

                        </span>
                    </button>
                </div>
            </div>

        </nav>
    </div>
</header>
    @RenderBody()
    <!-- info section -->
    <section class="info_section layout_padding2">
        <div class="container">
            <div class="info_logo">
                <h2>
                    CURBASHA
                </h2>
            </div>
            <div class="row">

                <div class="col-md-3">
                    <div class="info_contact">
                        <h5>
                            About Shop
                        </h5>
                        <div>
                            <div class="img-box">
                                <img src="~/images/location-white.png" width="18px" alt="">
                            </div>
                            <p>
                                Address
                            </p>
                        </div>
                        <div>
                            <div class="img-box">
                                <img src="~/images/telephone-white.png" width="12px" alt="">
                            </div>
                            <p>
                                +12 2323232323
                            </p>
                        </div>
                        <div>
                            <div class="img-box">
                                <img src="~/images/envelope-white.png" width="18px" alt="">
                            </div>
                            <p>
                                curbasha@gmail.com
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="info_info">
                        <h5>
                            Informations
                        </h5>
                        <p>
                            ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end info section -->
    <section class="container-fluid footer_section ">
        <div class="container">
            <p>
                &copy; 2022 All Rights Reserved
            </p>
        </div>
    </section>

       

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        var nav = $("#navbarSupportedContent");
        var btn = $(".custom_menu-btn");
        btn.click
        btn.click(function (e) {

            e.preventDefault();
            nav.toggleClass("lg_nav-toggle");
            document.querySelector(".custom_menu-btn").classList.toggle("menu_btn-style")
        });
    </script>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>