CurbashaApi/Controllers/Admin/SelectionsAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CurbashaApi.Areas.Identity.Entity;
using CurbashaApi.Data;
using Microsoft.AspNetCore.Authorization;
using System.Dynamic;

namespace CurbashaApi.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SelectionsAdminController : Controller
    {
        private readonly CurbashaApiContext _context;

        public SelectionsAdminController(CurbashaApiContext context)
        {
            _context = context;
        }

        // GET: SelectionsAdmin/Index
        public async Task<IActionResult> Index()
        {
            ViewBag.Products = _context.AspProducts.Select(p => p).ToList();
            return View(await _context.AspSelections.ToListAsync());
        }

        // GET: SelectionsAdmin/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SelectionsAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SelectionName,IsActive")] AspSelections aspSelection)
        {
            if (aspSelection != null)
            {
                if (!_context.AspSelections.Any(s => s.SelectionName.Equals(aspSelection.SelectionName))) {
                    _context.Add(aspSelection);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return Problem("Already exist. Try again");
                }
            }
            return View(aspSelection);
        }

        // GET: SelectionsAdmin/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.AspSelections == null)
            {
                return RedirectToAction("Error404", "Admin");
            }

            var aspSelections = await _context.AspSelections.FindAsync(id);
            if (aspSelections == null)
            {
                return RedirectToAction("Error404", "Admin");
            }
            return View(aspSelections);
        }

        // POST: SelectionsAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SelectionName,IsActive")] AspSelections aspSelections)
        {
            if (id != aspSelections.Id)
            {
                return RedirectToAction("Error404", "Admin");
            }

            if (aspSelections != null)
            {
                try
                {
                    _context.Update(aspSelections);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AspSelectionsExists(aspSelections.Id))
                    {
                        return RedirectToAction("Error404", "Admin");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aspSelections);
        }

        // GET: SelectionsAdmin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.AspSelections == null)
            {
                return RedirectToAction("Error404", "Admin");
            }

            var aspSelections = await _context.AspSelections
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aspSelections == null)
            {
                return RedirectToAction("Error404", "Admin");
            }

            return View(aspSelections);
        }

        // POST: SelectionsAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.AspSelections == null)
            {
                return Problem("Entity set 'CurbashaApiContext.AspSelections'  is null.");
            }
            var aspSelections = await _context.AspSelections.FindAsync(id);
            if (aspSelections != null)
            {
                _context.AspSelections.Remove(aspSelections);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AspSelectionsExists(int id)
        {
          return _context.AspSelections.Any(e => e.Id == id);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CurbashaApi/Controllers/OrderItemsAdminController.cs/SelectionsAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CurbashaApi.Areas.Identity.Entity;
using CurbashaApi.Data;
using Microsoft.AspNetCore.Authorization;

namespace CurbashaApi.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class SelectionsAdminController : Controller
    {
        private readonly CurbashaApiContext _context;

        public SelectionsAdminController(CurbashaApiContext context)
        {
            _context = context;
        }

        // GET: SelectionsAdmin/Index
        public async Task<IActionResult> Index()
        {
              return View(await _context.AspSelections.ToListAsync());
        }

        // GET: SelectionsAdmin/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SelectionsAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SelectionName,IsActive")] AspSelections aspSelection)
        {
            if (aspSelection != null)
            {
                if (!_context.AspSelections.Any(s => s.SelectionName.Equals(aspSelection.SelectionName))) {
                    _context.Add(aspSelection);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return Problem("Already exist. Try again");
                }
            }
            return View(aspSelection);
        }

        // GET: SelectionsAdmin/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.AspSelections == null)
            {
                return NotFound();
            }

            var aspSelections = await _context.AspSelections.FindAsync(id);
            if (aspSelections == null)
            {
                return NotFound();
            }
            return View(aspSelections);
        }

        // POST: SelectionsAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SelectionName,IsActive")] AspSelections aspSelections)
        {
            if (id != aspSelections.Id)
            {
                return NotFound();
            }

            if (aspSelections != null)
            {
                try
                {
                    _context.Update(aspSelections);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AspSelectionsExists(aspSelections.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aspSelections);
        }

        // GET: SelectionsAdmin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.AspSelections == null)
            {
                return NotFound();
            }

            var aspSelections = await _context.AspSelections
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aspSelections == null)
            {
                return NotFound();
            }

            return View(aspSelections);
        }

        // POST: SelectionsAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.AspSelections == null)
            {
                return Problem("Entity set 'CurbashaApiContext.AspSelections'  is null.");
            }
            var aspSelections = await _context.AspSelections.FindAsync(id);
            if (aspSelections != null)
            {
                _context.AspSelections.Remove(aspSelections);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AspSelectionsExists(int id)
        {
          return _context.AspSelections.Any(e => e.Id == id);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CurbashaApi/Views/SelectionsAdmin/Create.cshtml
@model CurbashaApi.Areas.Identity.Entity.AspSelections

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>AspSelections</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SelectionName" class="control-label"></label>
                <input asp-for="SelectionName" class="form-control" />
                <span asp-validation-for="SelectionName" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CurbashaApi/Views/SelectionsAdmin/Delete.cshtml
@model CurbashaApi.Areas.Identity.Entity.AspSelections

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AspSelections</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SelectionName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SelectionName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CurbashaApi/Views/SelectionsAdmin/Edit.cshtml
@model CurbashaApi.Areas.Identity.Entity.AspSelections

@{
        ViewData["Title"] = "Edit";
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>Edit</h1>

<h4>AspSelections</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SelectionName" class="control-label"></label>
                <input asp-for="SelectionName" class="form-control" />
                <span asp-validation-for="SelectionName" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CurbashaApi/Views/SelectionsAdmin/Index.cshtml
@model IEnumerable<CurbashaApi.Areas.Identity.Entity.AspSelections>

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var products = ViewBag.Products as IEnumerable<CurbashaApi.Areas.Identity.Entity.AspProduct>;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Sections</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.SelectionName)
                            </th>                            
                            <th>
                                @Html.DisplayNameFor(model => model.IsActive)
                            </th>
                            <th>
                                Product Count
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SelectionName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IsActive)
                                </td>
                                <td>
                                    @products.Where(p => p.SelectionId == item.Id).Count()
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "SelectionsAdmin", new { id = item.Id })">
                                        <i class="btn btn btn-info btn-sm">Edit</i>
                                    </a>
                                    <a href="@Url.Action("Delete", "SelectionsAdmin", new { id = item.Id })">
                                        <i class="btn btn-danger btn-sm">Delete</i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>