CurbashaApi/Controllers/Admin/ProductAdminController.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using CurbashaApi.Areas.Identity.Entity;
using CurbashaApi.Data;
using CurbashaApi.Models;
using CurbashaApi.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.Evaluation;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;

namespace CurbashaApi.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductAdminController : Controller
    {
        private readonly CurbashaApiContext _context;
        private readonly IWebHostEnvironment _environment;

        public ProductAdminController(CurbashaApiContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: /ProductAdmin/Index
        public IActionResult Index()
        {
            var products = _context.AspProducts.ToList();
            ViewBag.Sections = _context.AspSelections.Select(p => p).ToList();
            return View(products);
        }

        #region Create
        // GET: ProductAdmin/Create
        public IActionResult Create()
        {
            ViewBag.SelectionId = new SelectList(_context.AspSelections, "Id", "SelectionName");
            return View();
        }

        // POST: ProductAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NameProduct,Description,SelectionId,Price,IsActive")] AspProduct aspProduct)
        {
            aspProduct.AspSelections = _context.AspSelections.First(s => s.Id == aspProduct.SelectionId);

            if (aspProduct != null)
            {
                _context.AspProducts.Add(aspProduct);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.SelectionId = new SelectList(_context.AspSelections, "Id", "SelectionName", aspProduct.SelectionId);
            return View(aspProduct);
        }
        #endregion

        #region Edit
        // GET: ProductAdmin/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error404", "Admin");
            }
            AspProduct? product = await _context.AspProducts.FirstOrDefaultAsync(p => p.Id == id);
            if (product == null)
            {
                return RedirectToAction("Error404", "Admin");
            }
            ViewBag.SelectionId = new SelectList(_context.AspSelections, "Id", "SelectionName", product.SelectionId);
            return View(product);
        }

        // POST: ProductAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NameProduct,Description,SelectionId,Price,IsActive")] AspProduct product, IFormFile formFile)
        {
            if (id != product.Id)
            {
                return RedirectToAction("Error404", "Admin");
            }

            if (product != null)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return RedirectToAction("Error404", "Admin");
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewBag.SelectionId = new SelectList(_context.AspSelections, "Id", "SelectionName", product.SelectionId);
                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }
        #endregion

        #region Delete
        // GET: ProductAdmin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error404", "Admin");
            }
            AspProduct? product = await _context.AspProducts.FirstOrDefaultAsync(p => p.Id == id);
            if (product == null)
            {
                return RedirectToAction("Error404", "Admin");
            }
            return View(product);
        }

        // POST: ProductAdmin/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _context.AspProducts.FirstOrDefaultAsync(p => p.Id == id);

            if (product != null)
            {
                DeleteImageFromWWWRootFolder(product);
                _context.AspProducts.Remove(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }
        #endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Photo
        // GET: ProductAdmin/Photo/5
        [HttpGet]
        public async Task<IActionResult> Photo(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error404", "Admin");
            }
            AspProduct? product = await _context.AspProducts.FirstAsync(p => p.Id == id);
            if (product == null)
            {
                return RedirectToAction("Error404", "Admin");
            }
            ViewBag.SelectionId = new SelectList(_context.AspSelections, "Id", "SelectionName", product.SelectionId);
            return View(product);
        }

        // POST: ProductAdmin/Photo/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Photo(int id, AspProduct product, IFormFile formFile)
        {
            if (id != product.Id)
            {
                return RedirectToAction("Error404", "Admin");
            }
            product = await _context.AspProducts.FirstAsync(p => p.Id == id);
            if (product != null)
            {
                if (IsImage(formFile))
                {
                    var ImagePath = Path.Combine(_environment.WebRootPath, "images", "products",
                        $"{product.Id}.1.jpg");
                    if (System.IO.File.Exists(ImagePath))
                    {
                        DeleteImageFromWWWRootFolder(product);
                    }
                    string actionResult = ProcessUploadedFile(ImagePath, formFile);
                    ViewBag.Message = actionResult;
                }
                else
                    ViewBag.Message = "Not an image";

                return View(product);
            }

            return View(product);
        }
        #endregion


        [HttpPost]
        private string ProcessUploadedFile(string ImagePath, IFormFile formFile)
        {

            try
            {
                Guid guid = Guid.NewGuid();
                var stream = new FileStream(ImagePath, FileMode.Create);
                formFile.CopyToAsync(stream);
                return "File uploaded successfully.";
            }
            catch
            {
                return "Error while uploading the files.";
            }
        }

        private void DeleteImageFromWWWRootFolder(AspProduct product)
        {
            var CurrentImage = Path.Combine(_environment.WebRootPath, "images", "products",
                $"{product.Id}.1.jpg");
            if (System.IO.File.Exists(CurrentImage))
            {
                System.IO.File.Delete(CurrentImage);
            }
        }

        private bool IsImage(IFormFile formFile)
        {
            var imageTypes = new string[] {
                    "image/jpg",
                    "image/jpeg",
                    "image/png"
                };
            if (formFile == null || formFile.Length == 0)
            {
                return false;
            }
            else if (!imageTypes.Contains(formFile.ContentType))
            {
                return false;
            }
            return true;
        }

        private bool ProductExists(int id)
        {
            return _context.AspProducts.Any(e => e.Id == id);
        }
    }
}

CurbashaApi/Views/ProductAdmin/Create.cshtml
@model CurbashaApi.Areas.Identity.Entity.AspProduct

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


    <h1>Create</h1>

    <h4>Product</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="NameProduct" class="control-label"></label>
                    <input asp-for="NameProduct" class="form-control" />
                    <span asp-validation-for="NameProduct" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SelectionId" class="control-label"></label>
                    @Html.DropDownList("SelectionId", null, htmlAttributes: new { @class = "form-control" })
                    <span asp-validation-for="SelectionId" class="text-danger"></span>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                    </label>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

CurbashaApi/Views/ProductAdmin/Delete.cshtml
@model CurbashaApi.Areas.Identity.Entity.AspProduct
@{
    ViewData["Title"] = "Product";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SelectionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SelectionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameProduct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameProduct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger mr-2" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CurbashaApi/Views/ProductAdmin/Edit.cshtml
@model CurbashaApi.Areas.Identity.Entity.AspProduct

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NameProduct" class="control-label"></label>
                <input asp-for="NameProduct" class="form-control" />
                <span asp-validation-for="NameProduct" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SelectionId" class="control-label"></label>
                @Html.DropDownList("SelectionId", null, htmlAttributes: new { @class = "form-control" })
                <span asp-validation-for="SelectionId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CurbashaApi/Views/ProductAdmin/Index.cshtml
@model IEnumerable<CurbashaApi.Areas.Identity.Entity.AspProduct>

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    var sections = ViewBag.Sections as IEnumerable<CurbashaApi.Areas.Identity.Entity.AspSelections>;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Product</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.NameProduct)
                            </th>
                            <th>
                                Selection
                            </th>
                            <th>
                                Photo
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Price)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.IsActive)
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NameProduct)
                                </td>
                                <td>
                                    @sections.FirstOrDefault(s => s.Id == item.SelectionId).SelectionName
                                </td>
                                <td>
                                    @if (System.IO.File.Exists($"wwwroot/images/products/{@item.Id}.1.jpg"))
                                        {
                                    <img src="~/images/products/@item.Id.1.jpg" width="50" height="70"/>
                                        }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Price)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IsActive)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "ProductAdmin", new { id = item.Id })">
                                        <i class="btn btn btn-info btn-sm">Edit</i>
                                    </a>
                                    <a href="@Url.Action("Photo", "ProductAdmin", new { id = item.Id })">
                                        <i class="btn btn-warning btn-sm my-1">Photo</i>
                                    </a>
                                    <a href="@Url.Action("Delete", "ProductAdmin", new { id = item.Id })">
                                        <i class="btn btn-danger btn-sm">Delete</i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>

CurbashaApi/Views/ProductAdmin/Photo.cshtml
@model CurbashaApi.Areas.Identity.Entity.AspProduct

@{

    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Product Details</h2>

<div>
    <h4>Viewing details for @Model.NameProduct</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SelectionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SelectionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameProduct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameProduct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        @using (Html.BeginForm("Photo", "ProductAdmin", FormMethod.Post, new { @enctype = "multipart/form-data" }))
            {
            <dd>
                <form asp-action="Photo">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="file" name="formFile" />
                            <span class="text-danger">@ViewBag.Message</span>
                        </div>
                        @*if exist -> show photo*@
                        <div class="form-group">
                            <input type="submit" value="Upload photo" class="btn btn-primary" />
                        </div>
                    </div>
                </form>
            </dd>
            }
        </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>